export default {
  name: '柱状图',
  style: [{
    label: '全局样式',
    isExpand: true,
    children: [{
      label: '字体',
      name: 'fontFamily',
      type: 'fontFamily'
    }, {
      label: '柱子样式',
      children: [{
        label: '柱子宽度',
        name: 'barWidth',
        type: 'slider',
        value: 0,
        min: 0,
        max: 100,
        step: 1
      }, {
        label: '柱子圆角度',
        name: 'barBorderRadius',
        type: 'slider',
        value: 0,
        min: 0,
        max: 100,
        step: 1
      }, {
        label: '背景色',
        name: 'color',
        type: 'color'
      }]
    }, {
      label: '边距',
      children: [{
        label: '顶部',
        name: 'grid.top',
        type: 'number',
        value: 40
      }, {
        label: '底部',
        name: 'grid.bottom',
        type: 'number',
        value: 40
      }, {
        label: '左侧',
        name: 'grid.left',
        type: 'number',
        value: 40
      }, {
        label: '右侧',
        name: 'grid.right',
        type: 'number',
        value: 40
      }]
    }, {
      label: '值标签',
      name: 'label',
      type: 'checkbox',
      children: [{
        label: '字号',
        name: 'label.fontSize',
        type: 'number',
        value: 12
      }, {
        label: '颜色',
        name: 'label.color',
        type: 'color'
      }, {
        label: '字体粗细',
        name: 'label.fontWeight',
        type: 'fontweight'
      }, {
        label: '位置',
        name: 'label.position',
        type: 'position',
        value: 'inside'
      }]
    }]
  }, {
    label: 'x轴',
    name: 'x.show',
    type: 'checkbox',
    value: true,
    isExpand: true,
    children: [{
      label: '字号',
      name: 'x.fontSize',
      type: 'number',
      value: 12
    }, {
      label: '颜色',
      name: 'x.color',
      type: 'color'
    }, {
      label: '字体粗细',
      name: 'x.fontWeight',
      type: 'fontweight'
    }]
  }, {
    label: 'y轴',
    name: 'y.show',
    type: 'checkbox',
    value: true,
    isExpand: true,
    children: [{
      label: '字号',
      name: 'y.fontSize',
      type: 'number',
      value: 12
    }, {
      label: '颜色',
      name: 'y.color',
      type: 'color'
    }, {
      label: '字体粗细',
      name: 'y.fontWeight',
      type: 'fontweight'
    }]
  }, {
    label: '数据系列',
    isExpand: true
  }],
  data: [],
  event: []
};